---
name: Release

on:
  workflow_dispatch:
    inputs:
      app:
        type: string
        description: The name of the app to build
        required: true
      release:
        type: boolean
        description: Whether to release the app
        required: false
        default: false
  pull_request:
    branches: ["main"]
    paths: ["apps/**"]
  push:
    branches: ["main"]
    paths: ["apps/**"]

jobs:
  changed:
    name: Get Changed Apps
    runs-on: ubuntu-latest
    outputs:
      apps: ${{ steps.apps.outputs.apps }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - if: ${{ github.event_name != 'workflow_dispatch' }}
        name: Determine Changed Directories
        uses: tj-actions/changed-files@26a38635fc1173cc5820336ce97be6188d0de9f5 # v46.0.2
        id: changed-dirs
        with:
          dir_names: true
          dir_names_max_depth: "1"
          path: apps

      - name: Extract Metadata
        id: apps
        working-directory: apps
        run: |
          apps="${{ github.event_name == 'workflow_dispatch' && inputs.app || steps.changed-dirs.outputs.all_changed_and_modified_files }}"
          apps=$(printf "%s/metadata.yaml\n" ${apps})
          apps=$(yq eval-all --indent=0 --output-format=json "[.]" ${apps})
          echo "apps=${apps}" >> $GITHUB_OUTPUT

  build:
    needs: changed
    name: Build ${{ matrix.app.name }}
    uses: ./.github/workflows/image-build-action.yaml
    permissions:
      attestations: write
      contents: read
      id-token: write
      packages: write
    strategy:
      matrix:
        app: ${{ fromJSON(needs.changed.outputs.apps) }}
      fail-fast: false
    with:
      app: ${{ matrix.app.name }}
      version: ${{ matrix.app.version }}
      release: ${{ github.event_name == 'workflow_dispatch' && inputs.release || github.event_name == 'push' }}

  status:
    if: ${{ always() }}
    needs: build
    name: Build Success
    runs-on: ubuntu-latest
    steps:
      - name: Any jobs failed?
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1

      - name: All jobs passed or skipped?
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: echo "All jobs passed or skipped" && echo "${{ toJSON(needs.*.result) }}"
